# NumPy

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the `ndarray` object. This encapsulates n-dimensional arrays of **homogeneous** data types, with many operations being performed in compiled code for performance. There are several important differences between NumPy arrays and the standard Python sequences:

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.
- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.
- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.
- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays. In other words, in order to efficiently use much (perhaps even most) of today’s scientific/mathematical Python-based software, just knowing how to use Python’s built-in sequence types is insufficient - one also needs to know how to use NumPy arrays.

The points about sequence size and speed are particularly important in scientific computing. As a simple example, consider the case of multiplying each element in a 1-D sequence with the corresponding element in another sequence of the same length. If the data are stored in two Python lists, `a` and `b`, we could iterate over each element:

```python
c = []
for i in range(len(a)):
    c.append(a[i]*b[i])
```

This produces the correct answer, but if a and b each contain millions of numbers, we will pay the price for the inefficiencies of looping in Python. Furthermore, the coding work required increases with the dimensionality of our data. In the case of a 2-D array, we have to perform nested iterations.

NumPy gives us the best of both worlds: element-by-element operations are the “default mode” when an ndarray is involved, but the element-by-element operation is speedily executed by pre-compiled C code. In NumPy:

```python
c = a * b
```

This example illustrates two of NumPy's features which are the basis of much of its power: vectorization and broadcasting.

Vectorization describes the absence of any explicit looping, indexing, etc., in the code - these things are taking place, of course, just "behind the scenes" in optimized, pre-compiled C code. Vectorized code has many advantages, among which are:

- vectorized code is more concise and easier to read
- fewer lines of code generally means fewer bugs
- the code more closely resembles standard mathematical notation (making it easier, typically, to correctly code mathematical constructs)
- vectorization results in more "Pythonic" code. Without vectorization, our code would be littered with inefficient and difficult to read for loops.

Broadcasting is the term used to describe the implicit element-by-element behavior of operations; generally speaking, in NumPy all operations, not just arithmetic operations, but logical, bit-wise, functional, etc., behave in this implicit element-by-element fashion, i.e., they broadcast. Moreover, in the example above, a and b could be multidimensional arrays of the same shape, or a scalar and an array, or even two arrays of with different shapes, provided that the smaller array is "expandable" to the shape of the larger in such a way that the resulting broadcast is unambiguous.

## Installing NumPy

NumPy is included in most Python distributions. If not installed, you can checkout various installation approaches here: https://scipy.org/install.html

In [ ]:
import numpy as np

## NumPy Array

NumPy provides an N-dimensional array type, the `ndarray`, which describes a collection of "items" of the **same type**. The items can be indexed using for example N integers.

All `ndarrays` are **homogenous**: every item takes up the same size block of memory, and all blocks are interpreted in exactly the same way. How each item in the array is to be interpreted is specified by a separate data-type object, one of which is associated with every array. In addition to basic types (integers, floats, etc.), the data type objects can also represent data structures.

An item extracted from an array, e.g., by indexing, is represented by a Python object whose type is one of the array scalar types built in NumPy. The array scalars allow easy manipulation of also more complicated arrangements of data.

![NumPy array structure](https://docs.scipy.org/doc/numpy/_images/threefundamental.png)

## Array Creation Routines

### From existing data

`numpy.array(object, dtype=None)`: Create an array. `object` can be any array-like or sequence of data (e.g., list). `dtype` is the desired data-type for the array. If not given, then the type will be determined as the minimum type required to hold the objects in the sequence.

In [ ]:
# calculate BMIs for the following 20 people, heights (in) and weights (lb) are given
# 1 in is 0.0254 m and 1 lb is 0.453592 kg
heights_in = [74,74,72,72,73,69,69,71,76,71,73,73,74,74,69,70,73,75,78,79]
weights_lb = [180,215,210,210,188,176,209,200,231,180,188,180,185,160,180,185,189,185,219,230]

arr_heights_m = np.array(heights_in) * 0.0254
arr_weights_kg = np.array(weights_lb) * 0.453592



### Ones and Zeros

`numpy.zeros(<shape>, dtype=<type>)`: Return a new array of given shape and type, filled with zeros.

In [ ]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

`numpy.ones(<shape>, dtype=<type>)`: Return a new array of given shape and type, filled with ones.

In [ ]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

`numpy.full(<shape>, <fill_value>, dtype=<type>)`: Return a new array of given shape and type, filled with `fill_value`.

In [ ]:
np.full((3, 4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

`numpy.eye(<N>, <M>, k=<0>, dtype=<type>)`: Return a 2-D array with ones on the diagonal and zeros elsewhere. `M` is number of columns in the output. If `None`, defaults to `N`. `k` is index of the diagonal: 0 (the default) refers to the main diagonal, a positive value refers to an upper diagonal, and a negative value to a lower diagonal.

In [ ]:
np.eye(5, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

`numpy.identity(<n>, dtype=<type>)`: Return the identity array.

In [ ]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Numerical ranges

`numpy.arange(<start>, <stop>, <step>, dtype=<type>)`: Return evenly spaced values within a given interval.

In [ ]:
np.arange(10, 30, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

`numpy.linspace(<start>, <stop>, num=<50>, endpoint=<True>, dtype=<type>)`: Returns num evenly spaced samples, calculated over the interval [start, stop].

In [ ]:
np.linspace(10, 20, num=11)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

`numpy.logspace(<start>, <stop>, num=<50>, endpoint=<True>, base=<10.0>, dtype=<type>)`: Return numbers spaced evenly on a log scale.

In [ ]:
np.logspace(1, 4, num=4)

array([   10.,   100.,  1000., 10000.])

`numpy.geomspace(<start>, <stop>, num=<50>, endpoint=<True>, dtype=<type>)`: Return numbers spaced evenly on a log scale (a geometric progression).

In [ ]:
np.geomspace(1,1000, num=4)

array([   1.,   10.,  100., 1000.])

## Array Attributes

Array attributes reflect information that is intrinsic to the array itself. Generally, accessing an array through its attributes allows you to get and sometimes set intrinsic properties of the array without creating a new array. The exposed attributes are the core parts of an array and only some of them can be reset meaningfully without creating a new array.

### Array Layout

`ndarray.shape`: Tuple of array dimensions.

In [ ]:
diagonal = np.eye(6, 4)
diagonal

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
diagonal.shape

(6, 4)

In [ ]:
diagonal.shape = (4, 6)
diagonal

array([[1., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

`ndarray.ndim`: Number of array dimensions.

In [ ]:
diagonal.ndim

2

In [ ]:
diagonal.shape = (2, 3, 4)
diagonal

array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]],

       [[0., 0., 0., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
diagonal.ndim

3

`ndarray.size`: Number of elements in the array.

In [ ]:
diagonal.size

24

`ndarray.nbytes`: Total bytes consumed by the elements of the array.

In [ ]:
diagonal = np.linspace(100000, 999999, num=10000)
diagonal.nbytes

80000

### Date type

`ndarray.dtype`: Data-type of the array’s elements.

In [ ]:
diagonal.dtype

dtype('float64')

#### NumPy Built-in Scalar Types

The built-in scalar types are shown here: https://docs.scipy.org/doc/numpy/reference/arrays.scalars.html#arrays-scalars-built-in

The most common ones are: `int8`, `int16`, `int32`, `int64`, `uint8`, `uint8`, `uint16`, `uint32`, `uint64`, `float16`, `float32`, `float64`, `float96`, `float128`, `complex64`, `complex128`, `complex192`, `complex256`

In [ ]:
np.linspace(10, 50, num=10)

array([10.        , 14.44444444, 18.88888889, 23.33333333, 27.77777778,
       32.22222222, 36.66666667, 41.11111111, 45.55555556, 50.        ])

In [ ]:
np.linspace(10, 50, num=10, dtype=np.uint8)

array([10, 14, 18, 23, 27, 32, 36, 41, 45, 50], dtype=uint8)

### Other attributes

`ndarray.T`: Returns a view of the array with axes transposed.

In [ ]:
even_array = np.arange(0, 48, 2)
even_array.shape = (4, 6)
even_array

array([[ 0,  2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20, 22],
       [24, 26, 28, 30, 32, 34],
       [36, 38, 40, 42, 44, 46]])

In [ ]:
even_array.T

array([[ 0, 12, 24, 36],
       [ 2, 14, 26, 38],
       [ 4, 16, 28, 40],
       [ 6, 18, 30, 42],
       [ 8, 20, 32, 44],
       [10, 22, 34, 46]])

`ndarray.flat`: A 1-D iterator over the array.

In [ ]:
even_array.flat[2]

6

## Array Methods

An `ndarray` object has many methods which operate on or with the array in some fashion, typically returning an array result.

### Array Conversion

`ndarray.astype(<dtype>)`: Copy of the array, cast to a specified type.

In [ ]:
even_array.dtype

dtype('int64')

In [ ]:
even_array_float = even_array.astype(np.float16)
even_array_float

array([[ 0.,  2.,  4.,  6.,  8., 10.],
       [12., 14., 16., 18., 20., 22.],
       [24., 26., 28., 30., 32., 34.],
       [36., 38., 40., 42., 44., 46.]], dtype=float16)

`ndarray.fill(<value>)`: Fill the array with a scalar value.

In [ ]:
even_array.fill(100)
even_array

array([[100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100]])

### Shape Manipulation

`ndarray.reshape(<shape>)`: Returns an array containing the same data with a new shape.

In [ ]:
even_array.shape

(4, 6)

In [ ]:
even_array_long = even_array.reshape(12, 2)
even_array_long

array([[100, 100],
       [100, 100],
       [100, 100],
       [100, 100],
       [100, 100],
       [100, 100],
       [100, 100],
       [100, 100],
       [100, 100],
       [100, 100],
       [100, 100],
       [100, 100]])

In [ ]:
even_array.shape

(4, 6)

`ndarray.transpose(<axis>)`: Returns a view of the array with axes transposed.

In [ ]:
even_array_long.transpose()

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

`ndarray.flatten()`: Return a copy of the array collapsed into one dimension.

In [ ]:
even_array.flatten()

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

`ndarray.take(<indices>, <axis>)`: Return an array formed from the elements of a at the given indices.

In [ ]:
even_array = np.arange(0, 48, 2).reshape(4, 6)
even_array

array([[ 0,  2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20, 22],
       [24, 26, 28, 30, 32, 34],
       [36, 38, 40, 42, 44, 46]])

In [ ]:
even_array.take([3,8,12,22])

array([ 6, 16, 24, 44])

`ndarray.put(<indices>, <values>)`: Set a.flat[n] = values[n] for all n in indices.

In [ ]:
even_array.put([0,1,2,3], [100, 102, 104, 106])
even_array

array([[100, 102, 104, 106,   8,  10],
       [ 12,  14,  16,  18,  20,  22],
       [ 24,  26,  28,  30,  32,  34],
       [ 36,  38,  40,  42,  44,  46]])

`ndarray.sort(<axis=-1>)`: Sort an array, in-place.

In [ ]:
even_array.sort()
even_array

array([[  8,  10, 100, 102, 104, 106],
       [ 12,  14,  16,  18,  20,  22],
       [ 24,  26,  28,  30,  32,  34],
       [ 36,  38,  40,  42,  44,  46]])

In [ ]:
even_array.sort(axis=0)
even_array

array([[  8,  10,  16,  18,  20,  22],
       [ 12,  14,  28,  30,  32,  34],
       [ 24,  26,  40,  42,  44,  46],
       [ 36,  38, 100, 102, 104, 106]])

`ndarray.argsort(<axis>)`: Returns the indices that would sort this array.

In [ ]:
even_array = np.arange(48, 0, -2).reshape(4, 6)
even_array.argsort()

array([[5, 4, 3, 2, 1, 0],
       [5, 4, 3, 2, 1, 0],
       [5, 4, 3, 2, 1, 0],
       [5, 4, 3, 2, 1, 0]])

`ndarray.nonzero()`: Return the indices of the elements that are non-zero.

In [ ]:
even_array = np.arange(0, 48, 2).reshape(4, 6)
even_array.nonzero()

(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3,
        3]),
 array([1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4,
        5]))

### Calculation

Many of these methods take an argument named `axis`. In such cases,

- If `axis` is `None` (the default), the array is treated as a 1-D array and the operation is performed over the entire array. This behavior is also the default if self is a 0-dimensional array or array scalar. (An array scalar is an instance of the types/classes float32, float64, etc., whereas a 0-dimensional array is an ndarray instance containing precisely one array scalar.)
- If `axis` is an integer, then the operation is done over the given axis (for each 1-D subarray that can be created along the given axis).

Below is the list of calculation methods available as array methods:

- `ndarray.argmax([axis, out])`: Return indices of the maximum values along the given axis.
- `ndarray.min([axis, out, keepdims])`: Return the minimum along a given axis.
- `ndarray.argmin([axis, out])`: Return indices of the minimum values along the given axis of a.
- `ndarray.ptp([axis, out, keepdims])`: Peak to peak (maximum - minimum) value along a given axis.
- `ndarray.clip([min, max, out])`: Return an array whose values are limited to [min, max].
- `ndarray.conj()`: Complex-conjugate all elements.
- `ndarray.round([decimals, out])`: Return a with each element rounded to the given number of decimals.
- `ndarray.trace([offset, axis1, axis2, dtype, out])`: Return the sum along diagonals of the array.
- `ndarray.sum([axis, dtype, out, keepdims])`: Return the sum of the array elements over the given axis.
- `ndarray.cumsum([axis, dtype, out])`: Return the cumulative sum of the elements along the given axis.
- `ndarray.mean([axis, dtype, out, keepdims])`: Returns the average of the array elements along given axis.
- `ndarray.var([axis, dtype, out, ddof, keepdims])`: Returns the variance of the array elements, along given axis.
- `ndarray.std([axis, dtype, out, ddof, keepdims])`: Returns the standard deviation of the array elements along given axis.
- `ndarray.prod([axis, dtype, out, keepdims])`: Return the product of the array elements over the given axis
- `ndarray.cumprod([axis, dtype, out])`: Return the cumulative product of the elements along the given axis.
- `ndarray.all([axis, out, keepdims])`: Returns True if all elements evaluate to True.
- `ndarray.any([axis, out, keepdims])`: Returns True if any of the elements of a evaluate to True.

In [ ]:
even_array = np.arange(2, 26, 2).reshape(4, 3)
even_array

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

In [ ]:
even_array.min()

2

In [ ]:
even_array.max()

24

In [ ]:
even_array.sum()

156

In [ ]:
even_array.mean()

13.0

In [ ]:
even_array.std()

6.904105059069326

In [ ]:
even_array.cumsum()

array([  2,   6,  12,  20,  30,  42,  56,  72,  90, 110, 132, 156])

In [ ]:
even_array.prod()

1961990553600

In [ ]:
even_array.cumprod()

array([            2,             8,            48,           384,
                3840,         46080,        645120,      10321920,
           185794560,    3715891200,   81749606400, 1961990553600])

## Array Indexing and Slicing

`ndarrays` can be indexed using the standard Python x[obj] syntax, where `x` is the array and `obj` the selection.

The basic slice syntax is `i:j:k` where `i` is the starting index, `j` is the stopping index, and `k` is the step ($k \neq 0$)

In [ ]:
odd_array = np.arange(1, 49, 2).reshape(4, 6)
odd_array

array([[ 1,  3,  5,  7,  9, 11],
       [13, 15, 17, 19, 21, 23],
       [25, 27, 29, 31, 33, 35],
       [37, 39, 41, 43, 45, 47]])

In [ ]:
odd_array[0]

array([ 1,  3,  5,  7,  9, 11])

In [ ]:
odd_array[0,3]

7

In [ ]:
odd_array[:,1]

array([ 3, 15, 27, 39])

In [ ]:
odd_array[::2]

array([[ 1,  3,  5,  7,  9, 11],
       [25, 27, 29, 31, 33, 35]])

In [ ]:
odd_array[::2, 2]

array([ 5, 29])

In [ ]:
odd_array[::2,::2]

array([[ 1,  5,  9],
       [25, 29, 33]])

Ellipsis (`...`) expand to the number of : objects needed to make a selection tuple of the same length as `ndarray.ndim`. There may only be a single ellipsis present.

In [ ]:
odd_array[...]

array([[ 1,  3,  5,  7,  9, 11],
       [13, 15, 17, 19, 21, 23],
       [25, 27, 29, 31, 33, 35],
       [37, 39, 41, 43, 45, 47]])

In [ ]:
odd_array[1,...]

array([13, 15, 17, 19, 21, 23])

In [ ]:
odd_array = odd_array.reshape(2,3,4)
odd_array

array([[[ 1,  3,  5,  7],
        [ 9, 11, 13, 15],
        [17, 19, 21, 23]],

       [[25, 27, 29, 31],
        [33, 35, 37, 39],
        [41, 43, 45, 47]]])

In [ ]:
odd_array[1,...]

array([[25, 27, 29, 31],
       [33, 35, 37, 39],
       [41, 43, 45, 47]])

In [ ]:
odd_array[...,1]

array([[ 3, 11, 19],
       [27, 35, 43]])

In [ ]:
odd_array[:,1,:]

array([[ 9, 11, 13, 15],
       [33, 35, 37, 39]])

### Integer Array Indexing

Integer array indexing allows selection of arbitrary items in the array based on their N-dimensional index. Each integer array represents a number of indexes into that dimension.

In [ ]:
odd_array = odd_array.reshape(4, 6)
odd_array

array([[ 1,  3,  5,  7,  9, 11],
       [13, 15, 17, 19, 21, 23],
       [25, 27, 29, 31, 33, 35],
       [37, 39, 41, 43, 45, 47]])

In [ ]:
odd_array[[0, 3],:]

array([[ 1,  3,  5,  7,  9, 11],
       [37, 39, 41, 43, 45, 47]])

In [ ]:
odd_array[:,[1,2,4]]

array([[ 3,  5,  9],
       [15, 17, 21],
       [27, 29, 33],
       [39, 41, 45]])

### Boolean array indexing

This advanced indexing occurs when obj is an array object of Boolean type, such as may be returned from comparison operators.

In [ ]:
even_vector = np.arange(0,31, 2)
even_vector

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [ ]:
even_vector < 10

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [ ]:
even_vector[even_vector < 10]

array([0, 2, 4, 6, 8])

In [ ]:
even_vector[even_vector >= even_vector.mean()]

array([16, 18, 20, 22, 24, 26, 28, 30])

In [ ]:
even_vector * (np.abs(np.sin(even_vector)) < 0.5)

array([ 0,  0,  0,  6,  0,  0,  0,  0, 16,  0,  0, 22,  0,  0, 28,  0])

In [ ]:
even_vector.shape = (4, 4)
even_vector

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [ ]:
even_vector * (even_vector % 5 == 0)

array([[ 0,  0,  0,  0],
       [ 0, 10,  0,  0],
       [ 0,  0, 20,  0],
       [ 0,  0,  0, 30]])

## Random Sampling

NumPy provides several functions for generating random values, including samples from well-known probability distributions. All returned samples are of type ndarray, so they can easily be used in operations with other NumPy ndarrays. To see a complete list of available random generation functions, visit the following link:

https://docs.scipy.org/doc/numpy-1.15.0/reference/routines.random.html

`numpy.random.random(<size>)`: Return random floats in the interval [0.0, 1.0).

In [ ]:
np.random.random(10)

array([0.37588979, 0.09898003, 0.75155888, 0.23674366, 0.16667968,
       0.35289885, 0.87308844, 0.71099108, 0.38002111, 0.96284009])

`numpy.random.randint(<low>, <high>)`: Return random integers from `low` (inclusive) to `high` (exclusive).

In [ ]:
np.random.randint(100, 200, 10)

array([124, 129, 150, 115, 162, 123, 121, 125, 181, 199])

`numpy.random.exponential(<scale>, <size>)`: Draw samples from an exponential distribution with a specific `scale` parameter.

In [ ]:
np.random.exponential(1, 10)

array([1.43975149, 0.02075923, 1.27139783, 1.69609285, 0.16906979,
       1.82917166, 1.42160387, 0.1242631 , 0.45070706, 0.04561556])

`numpy.random.normal(<loc>, <scale>, <size>)`: Draw random samples from a normal (Gaussian) distribution with the mean of `loc` and standard deviation of `scale`.

In [ ]:
np.random.normal(0, 3, 10)

array([-2.98426257,  3.81045098,  3.64862437,  1.80653591, -1.11453935,
        5.20071873,  0.02625636, -3.44066097, -0.92866332,  2.77674338])

`numpy.random.uniform(<low>, <high>, <size>)`: Draw samples from a uniform distribution.

In [ ]:
np.random.uniform(10, 20, 10)

array([18.8576768 , 19.03876096, 14.93972728, 12.93926026, 12.4186932 ,
       19.02100285, 11.52120654, 19.85078574, 13.01017065, 19.60129023])

`numpy.random.seed(<seed>)`: Seed the generator, so you can generate the same random numbers using the same seed. This helps replicating the same scenario again.

In [ ]:
np.random.seed(14)
# the following always results in the same set of random variables
np.random.random(10)

array([0.51394334, 0.77316505, 0.87042769, 0.00804695, 0.30973593,
       0.95760374, 0.51311671, 0.31828442, 0.53919994, 0.22125494])